### PR TITLE
Add .gitattributes for normalizing end of lines

### LINKED ISSUE #203: Prettier show all files with error because of default
Clone repository and run "yarn test" - prettier will show error in files because of end of lines. There is no prettier config, so it expect "lf" on end of line (from version 2.0.0 - https://prettier.io/docs/en/options.html#end-of-line) but currenty there is "crlf" in files.
I can prepare PR but what is right option: add .prettierrc with "crlf" end of line configuration value or change end of line in source files to "lf"?

### PR DESCRIPTION
**Pull request by peter-spireng**
As Prettier default expect "lf" on line endings, we need to normalize them with gitattributes  - fixes #203

### CODE REVIEW

**Comment by alexander-akait** [comment]
Can you regenerate lock file to fix security problem?

**Comment by peter-spireng** [comment]
Lock file regenerated

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by peter-spireng** [comment]
Done, also fixed commit message because of commitlint. Hopefully, it is all...

**Comment by peter-spireng** [comment]
@alexander-akait can you please aprove workflow?

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
