### PR TITLE
#19: added support for MS DOS style and UNC absolute paths used in Windows

### PR DESCRIPTION
**Pull request by Auxx**
I did not modify unit tests, because I'm not familiar with travis, sorry.

### CODE REVIEW

**Comment by sokra** [comment]
Please add tests: https://github.com/webpack/loader-utils/blob/master/test/index.js#L12-L30

`npm test` runs the tests, no need to be familiar with travis.

**Comment by Auxx** [comment]
@sokra I've added the tests for all cases I could imagine and while writing them I've found some other scenarios which were not previously covered by my patch, so I made necessary changes to the code and also added isWindowsPath() function to detect if path is in MS format.

**Comment by sokra** [comment]
* Relative windows paths should not be allowed
  * i. e. `name?{"a":"\\"}` would be detected wrong
  * windows paths are allows absolute
  * (one can use relative unix paths to navigate windows filesystems)
* don't expose `isWindowsPath`

**Comment by Auxx** [comment]
@sokra I've removed all of Windows specific relative path handling, all should be fine now.

**Comment by Auxx** [comment]
@sokra any news on merging?

**Pull request merged**
