### PR TITLE
Update license in package.json

### PR DESCRIPTION
**Pull request by baderbuddy**
Updating license metadata to be MIT

### CODE REVIEW

**Comment by jhnns** [comment]
The module is licensed under the JS foundation license, hence JSF

**Comment by baderbuddy** [comment]
Could you link to this license? The license file in the git repo looks like MIT, I looked at another jsf project and it's licensed under Apache.

**Comment by jhnns** [comment]
Sorry, you're right. We've changed it back to MIT.

**Comment by jhnns** [comment]
#66

**Pull request closed without merging**
