### PR TITLE
fix: fix regexp replace for contenthash|hash fields in interpolateName

### PR DESCRIPTION
**Pull request by Delagen**
Double || breaks some specific cases, moreover this is pattern error https://regex101.com/r/ReFLZL/1

### CODE REVIEW

**Comment by Delagen** [comment]
This fixed in 1.2.2. But I don't think that double || is suitable there

**Comment by evilebottnawi** [comment]
@Delagen yep, will fix it in near future

**Comment by Delagen** [comment]
Found seems Node.JS parse this as empty string, so
```
[
      '/lib/components/modal/modal.css',
      '[name].[md5::base64:20].[ext]',
      'test content',
      'modal.1n8osQznuT8jOAwdzg_n.css',
    ],
```
this works as hash or contenthash

**Comment by evilebottnawi** [comment]
@Delagen What? Please clarify

**Comment by Delagen** [comment]
this is valid token per this Regexp
```
[md5::base64:20]
```
and replaced with hash

**Comment by evilebottnawi** [comment]
@Delagen i can't understand you :smile: Can you provide examples what doesn't work as expected?

**Comment by Delagen** [comment]
Old version:
[name].[md5::base64:20].[ext] => modal.1n8osQznuT8jOAwdzg_n.css
My version:
[name].[md5::base64:20].[ext] => modal.[md5::base64:20].css

**Comment by evilebottnawi** [comment]
@Delagen looks we have bug in regexp before, so you can use `[name].[md5::base64:20].[ext]`, but it is invalid, you should use `[<hashType>:hash:<digestType>:<length>]` so you need use `[md5:hash:base64:20]`

**Comment by Delagen** [comment]
This bug persist in current version

**Comment by Delagen** [comment]
Sure you fixed this

**Pull request closed without merging**
