### PR TITLE
#54

### PR DESCRIPTION
**Pull request by xutou12**

### CODE REVIEW

**Comment by jhnns** [comment]
Thx for your suggestions @xutou12. That looks really good 👍

Could you rewrite your pull-request so that it matches only the first `?` character? With your proposed change, configs that contain `?` could be malformed.

**Comment by jhnns** [comment]
I think, this also fixes #37

**Comment by jhnns** [comment]
Oh, no, unfortunately not. But I'll pull that in because of the tests :)

**Comment by xutou12** [comment]
Oh, my fault, I did not consider comprehensively, Thank you~

**Pull request merged**
